### ISSUE TITLE
Declention game

### ISSUE THREAD

**Issue by visjble** [fpw/llpsi-net#2]
Not entirely sure how to play.

**Comment by fpw** [comment]
Hi,

the site is not ready yet, so sorry if things aren't self-explanatory yet. 

In the first step, you select your current LLPSI chapter. The vocabulary slider will determine which words will be used and only select words that were introduces in or before the selected chapter. The grammar slider will select which grammatical concepts you are supposed to know. This is also shown in the table below the sliders.

When the game starts, it will show you a few words in their nominative form. The words will also include a preposition or a question word. These determine the case - for example, if the first word is "post", you're supposed to decline everything in accusative since that's the matching case for this preposition.

You can always click on "Reveal answer" to see what the answer to the current problem is supposed to be.

Hope that helps!

**Comment by visjble** [comment]
Looking promising, thank you
